WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/Admin/Models/Entites/US.cs
namespace WebsiteBanHang.Areas.Admin.Models.Entites
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class US
    {
        [Key]
        [StringLength(100)]
        [Display(Name ="Tên Tài Khoản")]
        [Required(ErrorMessage ="Nhập {0}")]
        public string username { get; set; }

        [StringLength(100)]
        [Display(Name ="Mật Khẩu")]
        [Required(ErrorMessage ="Nhập {0}")]
        public string password { get; set; }

        [StringLength(100)]
        [Display(Name ="Họ Và Tên")]
        [Required(ErrorMessage ="Nhập {0}")]
        public string fullname { get; set; }
    }
}

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/User/Models/US.cs
namespace WebsiteBanHang.Areas.User.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class US
    {
        [Key]
        [StringLength(100)]
        public string username { get; set; }

        [StringLength(100)]
        public string password { get; set; }

        [StringLength(100)]
        public string fullname { get; set; }
    }
}

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/Admin/Controllers/USController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.Admin.Models.Entites;
using WebsiteBanHang.Areas.Admin.Models.DAO;
using System.IO;

namespace WebsiteBanHang.Areas.Admin.Controllers
{
    public class USController : Controller
    {
        // GET: Admin/US
        WebsiteModel db;
        public USController()
        {
            db = new WebsiteModel();
        }
        public ActionResult Index(string timkiem, int PageNum = 1, int PageSize = 2)
        {
            UserDAO dao = new UserDAO();
            return View(dao.ListUS(timkiem, PageNum, PageSize));
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(US u)
        {
            if (ModelState.IsValid)
            {
                UserDAO dao = new UserDAO();
                dao.Add(u);
                return RedirectToAction("Index");
            }
            else
                return View(u);
            
        }
        public ActionResult Edit(string id)
        {
            UserDAO dao = new UserDAO();
            US u = new US();
            u = dao.GetIdUS(id);
            return View(u);
        }
        [HttpPost]
        public ActionResult Edit(US u)
        {
            if (ModelState.IsValid)
            {
                UserDAO dao = new UserDAO();
                dao.Edit(u);
                return RedirectToAction("Index");
            }
            else
                return View(u);
        }
        public ActionResult Delete(string id)
        {
            UserDAO dao = new UserDAO();
            dao.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/US/Create.cshtml
@model WebsiteBanHang.Areas.Admin.Models.Entites.US

@{
    ViewBag.Title = "Create";

}

<h2>Thêm Mới Tài Khoản</h2>

@using (Html.BeginForm("Create", "US", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fullname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fullname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/US/Edit.cshtml
@model WebsiteBanHang.Areas.Admin.Models.Entites.US

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh Sửa Tài Khoản</h2>

@using (Html.BeginForm("Edit", "US", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.username)
    @*<div class="form-group">
        @Html.LabelFor(model => model.username, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
        </div>
    </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fullname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fullname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fullname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/Admin/Views/US/Index.cshtml
@model  PagedList.IPagedList<WebsiteBanHang.Areas.Admin.Models.Entites.US>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<h2>Quản Lý Tài Khoản</h2>
<form action="Index" method="get">
    <div class="row">
        <div class="col-md-3">
            <input type="text" placeholder="Search" name="timkiem">
        </div>
        

        <div class="col-md-2">
            <button type="submit">Tim kiếm </button>
        </div>
    </div>
</form>
<div class="row">
    <div class="col-12">
        <div class="card">
           
            <!-- /.card-header -->
            <div class="card-body">
                <p>
                    @Html.ActionLink("Thêm mới", "Create")
                </p>
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>
                                Tên Đăng Nhập 
                            </th>
                            <th>
                                Mật Khẩu
                            </th>
                            <th>
                                Họ Tên 
                            </th>
                           
                            <th>Chức Năng</th>
                        </tr>
                    </thead>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.username)
                             
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.password)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.fullname)
                            </td>
                           
                            <td>
                                @Html.ActionLink("Sửa", "Edit", new { id = item.username}) |
                                     @*@Html.ActionLink("Delete", "Delete", new { id = item.username })*@
                                <a href="~/Admin/US/Delete/@item.username" onclick="return confirm('Bạn chắc chắn muốn xóa?')">
                                    <span>Xóa</span>
                                </a>
                                @*@Ajax.ActionLink("Xóa", "Delete", new AjaxOptions
                           {
                               Confirm = "bạn có muốn Xóa tài khoản này không", 
                               OnComplete = ""
                           });*@
                            </td>
                        </tr>
                    }

                </table>
                <div class="col-sm-12 col-md-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        @Html.PagedListPager(Model, PageNum => Url.Action("Index", new { PageNum }))
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
    <!-- /.card -->
</div>
<!-- /.col -->
<style>

    /* thiết lập style cho thẻ a */
    .pagination li a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
        transition: background-color .3s;
    }
    /* thiết lập style cho class active */
    .pagination li.active a {
        background-color: dodgerblue;
        color: white;
    }
    /* thêm màu nền khi người dùng hover vào class không active */
    .pagination li:hover:not(.active) {
        background-color: #ddd;
    }
</style>