WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/User/Controllers/LaptopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.User.Models;
using PagedList;

namespace WebsiteBanHang.Areas.User.Controllers
{
    public class LaptopController : Controller
    {
        // GET: User/Laptop
        LaptopModel db = new LaptopModel();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PatialSanPhamMoi()
        {
            var lstLaptopMoi = db.SanPham.Take(6).ToList();
            return View(lstLaptopMoi);
        }
/*        public ActionResult PatialFullSanPham(int PageNum = 1, int PageSize = 12)
        {
            var lstLaptop = db.SanPham.OrderBy(n => n.MaLap);
            return View(lstLaptop.ToPagedList(PageNum, PageSize));
        }*/
        public ActionResult PatialFullSanPham(string ftimkiem = "")
        {
            List<SanPham> lstLaptop;
          //  lstLaptop = db.SanPham.Take(12).ToList();
            if (ftimkiem == "" || ftimkiem == null)
            {
                lstLaptop = db.SanPham.Take(12).ToList();
        
            }
            else
            {
                lstLaptop = db.SanPham.Where(x => x.TenLap.Contains(ftimkiem)).Take(12).ToList();      
            }
            
            return View(lstLaptop);
        }
        public ActionResult XemChiTiet(int malap = 0)
        {
            SanPham Chitiet = db.SanPham.SingleOrDefault(n => n.MaLap == malap);
            if(Chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(Chitiet);
        }

    }
}

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/User/Controllers/LoaiLaptopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Areas.User.Models;
using PagedList;
using PagedList.Mvc;
namespace WebsiteBanHang.Areas.User.Controllers
{
    public class LoaiLaptopController : Controller
    {
        // GET: User/LoaiLaptop
        LaptopModel db = new LaptopModel();
        public ActionResult PatialLoaiLaptop()
        {

            return View(db.TheLoai.ToList());
        }
        /*        public ActionResult XemLoaiLap(int Maloai = 0)
                {
                    List<SanPham> lstLap = db.SanPham.Where(x => x.MaLoai == Maloai).Take(12).OrderBy(x => x.GiaBan).ToList();

                    return View(lstLap);

                }*/
        public ActionResult XemLoaiLap(int Maloai = 0, int PageNum = 1, int PageSize = 5)
        {
            IQueryable<SanPham>  lstLap = db.SanPham.Where(x => x.MaLoai == Maloai).OrderBy(n => n.MaLap);
            ViewBag.Ml = Maloai;
            return View(lstLap.ToPagedList(PageNum,PageSize));

        }

    }
}

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/User/Views/LoaiLaptop/PatialLoaiLaptop.cshtml
@using WebsiteBanHang.Areas.User.Models;
@model List<TheLoai>

<div class="promo-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @{
                foreach (var item in Model)
                {
                    
                    <div class="col-md-3 col-sm-6">  
                        
                                        <div class="single-promo promo1">                                         
                                            <i class="fa fa-laptop"></i>
                                            <a href="@Url.Action("XemLoaiLap",new {@Maloai = item.MaLoai })"> @item.TenLoai </a>
                                        </div>                              
                    </div>
                }
            } 
        
        </div>
    </div>
</div> <!-- End promo area -->

WebOfDao/WebsiteBanHang/WebsiteBanHang/Areas/User/Views/LoaiLaptop/XemLoaiLap.cshtml
@using WebsiteBanHang.Areas.User.Models;
@using PagedList.Mvc;
@model  PagedList.PagedList<SanPham>
@{
    ViewBag.Title = "XemLoaiLap";
    Layout = "~/Areas/User/Views/Layout/NguoiDungLayout.cshtml";
}


<div class="slider-area">
    <!-- Slider -->
    <div class="block-slider block-slider4">
        <ul class="" id="bxslider-home4">
            <li>
                <img src="~/Areas/User/Content/img/h4-slide.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        iPhone <span class="primary">6 <strong>Plus</strong></span>
                    </h2>
                    <h4 class="caption subtitle">Dual SIM</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
            <li>
                <img src="~/Areas/User/Content/img/h4-slide2.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        by one, get one <span class="primary">50% <strong>off</strong></span>
                    </h2>
                    <h4 class="caption subtitle">school supplies & backpacks.*</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
            <li>
                <img src="~/Areas/User/Content/img/h4-slide3.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        Apple <span class="primary">Store <strong>Ipod</strong></span>
                    </h2>
                    <h4 class="caption subtitle">Select Item</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
            <li>
                <img src="~/Areas/User/Content/img/h4-slide4.png" alt="Slide">
                <div class="caption-group">
                    <h2 class="caption title">
                        Apple <span class="primary">Store <strong>Ipod</strong></span>
                    </h2>
                    <h4 class="caption subtitle">& Phone</h4>
                    <a class="caption button-radius" href="#"><span class="icon"></span>Shop now</a>
                </div>
            </li>
        </ul>
    </div>
    <!-- ./Slider -->
</div>

@* Chen vao partial the loai laptop*@
@Html.Action("PatialLoaiLaptop", "LoaiLaptop");

<div class="product-widget-area">
    <div class="zigzag-bottom"></div>
    <div class="container">
        <div class="row">
            @{
                foreach (var item in Model)
                {
                    <div class="col-md-4 col-sm-6">
                        <div class="single-shop-product">
                            <div class="product-upper">
                                <img src="~/Areas/Admin/Content/Photo/@item.AnhBia" alt="" style="height:300px; width: 300px;">
                            </div>
                            <h2><a href="@Url.Action("XemChiTiet","Laptop",new {@malap = item.MaLap })">@item.TenLap</a></h2>
                            <div class="product-carousel-price">
                                <ins>@item.GiaBan </ins>
                            </div>

                            <div class="product-option-shop">
                                <a class="add_to_cart_button" data-quantity="1" data-product_sku="" data-product_id="70" rel="nofollow" href="/canvas/shop/?add-to-cart=70">Add to cart</a>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
@*    <div>
        <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
            @Html.PagedListPager(Model, PageNum => Url.Action("XemLoaiLap", new { PageNum }))
        </div>
    </div>*@

</div> <!-- End product widget area -->
<div>
    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate" style=" margin-left: 90px;">
        @Html.PagedListPager(Model, PageNum => Url.Action("XemLoaiLap", new { PageNum, @Maloai = ViewBag.Ml }))
    </div>
</div>

<!-- End product widget area -->
<style>
    /* thiết lập style cho thẻ a */
    .pagination li a {
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
        transition: background-color .3s;
    }
    /* thiết lập style cho class active */
    .pagination li.active a {
        background-color: dodgerblue;
        color: white;
    }
    /* thêm màu nền khi người dùng hover vào class không active */
    .pagination li:hover:not(.active) {
        background-color: #ddd;
    }
</style>